#! /bin/bash
set -e

checkdir=${1-/check}

do_check () {
    pkg=${1}
    echo Checking "$pkg"
    cd `dirname $pkg`

    R -q -f /usr/local/bin/install-deps.R "$pkg"

    R CMD check $CHECK_ARGS $pkg

    packagename=$(basename $pkg | sed "s/_.*$//")
    cd ${packagename}.Rcheck
    fail=false
    exfile="${packagename}-Ex.Rout"
    pattern='UndefinedBehaviorSanitizer\|AddressSanitizer'
    if [[ -f "${exfile}" ]] && grep -q ${pattern} ${exfile}; then
        fail=true
        echo ----------------------------------------------------------
        echo ${exfile}
        echo ----------------------------------------------------------
        cat ${exfile}
        echo ----------------------------------------------------------
    fi
    testfiles=$(ls tests | grep ".Rout.fail$")
    for f in $testfiles; do
        if grep -q ${pattern} tests/$f; then
            fail=true
            echo ----------------------------------------------------------
            echo tests/${f}
            echo ----------------------------------------------------------
            cat tests/${f}
            echo ----------------------------------------------------------
        fi
    done
    if [[ "$fail" = "true" ]]; then exit 1; fi
}

for pkg in `ls $checkdir/*.tar.gz`; do
    do_check "$pkg"
done
