
FROM ubuntu:26.04

WORKDIR /root

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -y && \
    apt-get install -y curl xz-utils && \
    curl -LO https://poppler.freedesktop.org/poppler-24.05.0.tar.xz && \
    tar xf poppler-*.xz && \
    rm poppler-*.xz

# ------------------------------------------------------------------------------------
# clang 23

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get install -y gpg && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl https://apt.llvm.org/llvm-snapshot.gpg.key | \
      gpg --dearmor -o /etc/apt/keyrings/apt.llvm.org.gpg

RUN echo "deb [signed-by=/etc/apt/keyrings/apt.llvm.org.gpg] http://apt.llvm.org/resolute/ llvm-toolchain-resolute-23 main" | \
  tee -a /etc/apt/sources.list.d/llvm.list

RUN apt-get update -y && \
    apt-get install -y clang-23 libc++abi-23-dev libc++-23-dev libomp-23-dev flang-23 && \
    apt-get install -y pkg-config make gfortran && \
    apt-get clean

RUN ln -s /usr/bin/clang-23 /usr/bin/clang && \
    ln -s /usr/bin/clang++-23 /usr/bin/clang++

# dependencies
RUN apt-get install -y cmake libnss3-dev \
    libtiff-dev liblcms2-dev libopenjp2-7-dev \
    libboost1.90-all-dev libfreetype-dev libfontconfig-dev \
    libcurl4-openssl-dev qtbase5-dev

RUN cd poppler-* && \
    mkdir build && \
    cd build && \
    CC=clang CXX=clang++ CXXFLAGS="-stdlib=libc++ -O3 -g" LDFLAGS="-stdlib=libc++ -lc++ -lc++abi" \
      cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/clang \
      -DCMAKE_BUILD_TYPE=release -DENABLE_QT6=OFF -DENABLE_GPGME=OFF && \
    make

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y checkinstall llvm-libunwind1 && \
    cd poppler-* && \
    mkdir -p /usr/share/doc/poppler-clang23/ && \
    cp COPYING NEWS ChangeLog README.md /usr/share/doc/poppler-clang23/ && \
    echo /usr/share/doc/poppler-clang23/COPYING > /tmp/xlist && \
    echo /usr/share/doc/poppler-clang23/NEWS >> /tmp/xlist && \
    echo /usr/share/doc/poppler-clang23/aChangeLog >> /tmp/xlist && \
    echo /usr/share/doc/poppler-clang23/README.md >> /tmp/xlist && \
    cd build && \
    checkinstall -y -D --pkgname poppler-clang23 \
    --fstrans=no \
    --pkgversion $(basename `pwd` | sed 's/^[^-]*-//') \
    --maintainer "csardi.gabor@gmail.com" \
    --include /tmp/xlist \
    --requires 'libc++1,libc++abi1,llvm-libunwind1,libc6,libgcc-s1,libopenjp2-7,liblcms2-2,libnss3' \
    --arch $(dpkg --print-architecture) \
    --pkglicense "See COPYING file."

RUN cp poppler-*/build/poppler-clang*.deb /root/

COPY build.sh /root/build.sh
