
FROM ubuntu:22.04

WORKDIR /root

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -y && \
    apt-get install -y curl && \
    curl -LO https://imagemagick.org/archive/ImageMagick.tar.gz && \
    tar xzf ImageMagick.tar.gz && \
    rm ImageMagick.tar.gz

# ------------------------------------------------------------------------------------
# clang 21, gfortran-12

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -y && \
    apt-get install -y gnupg curl && \
    echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-21 main" \
         > /etc/apt/sources.list.d/llvm.list && \
    echo "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-21 main" \
         >> /etc/apt/sources.list.d/llvm.list && \
    curl -L https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
    apt-get update -y && \
    apt-get install -y clang-21 libc++abi-21-dev libc++-21-dev libomp-21-dev libunwind-21-dev && \
    apt-get install -y pkg-config make

RUN ln -s /usr/bin/clang-21 /usr/bin/clang && \
    ln -s /usr/bin/clang++-21 /usr/bin/clang++

# dependencies
RUN apt-get install -y libjpeg8-dev libpng-dev libtiff-dev

RUN cd ImageMagick-* && \
    ./configure --prefix=/usr/local/clang CC=clang CXX=clang++ \
        'CXXFLAGS=-stdlib=libc++ -O3 -g' \
        LDFLAGS=-stdlib=libc++ 'LIBS=-lc++ -lc++abi' && \
    make

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y checkinstall

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y checkinstall && \
    cd ImageMagick-* && \
    mkdir -p /usr/share/doc/imagemagick-clang21/ && \
    cp LICENSE README.md /usr/share/doc/imagemagick-clang21/ && \
    echo /usr/share/doc/imagemagick-clang21/LICENSE > /tmp/xlist && \
    echo /usr/share/doc/imagemagick-clang21/README.md >> /tmp/xlist && \
    checkinstall -y -D --pkgname imagemagick-clang21 \
    --pkgversion $(basename `pwd` | sed 's/^[^-]*-//') \
    --maintainer "csardi.gabor@gmail.com" \
    --include /tmp/xlist \
    --requires 'libc++1,libc++abi1,llvm-libunwind1,libc6,libgcc-s1,libomp5,zlib1g,libxml2,liblzma5,libpng16-16,libjpeg-turbo8,libtiff5,libjbig0' \
    --arch $(dpkg --print-architecture) \
    --pkglicense "See LICENSE file."

RUN cp ImageMagick-*/imagemagick-clang21*.deb /root/

COPY build.sh /root/build.sh
