
FROM ubuntu:26.04

WORKDIR /root

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -y && \
    apt-get install -y curl xz-utils && \
    curl -LO https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-30/ImageMagick-7.1.2-30.tar.xz && \
    tar xf ImageMagick-*.tar.xz && \
    rm ImageMagick-*.tar.xz

# ------------------------------------------------------------------------------------
# clang 23

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get install -y gpg && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl https://apt.llvm.org/llvm-snapshot.gpg.key | \
      gpg --dearmor -o /etc/apt/keyrings/apt.llvm.org.gpg

RUN echo "deb [signed-by=/etc/apt/keyrings/apt.llvm.org.gpg] http://apt.llvm.org/resolute/ llvm-toolchain-resolute-23 main" | \
  tee -a /etc/apt/sources.list.d/llvm.list

RUN apt-get update -y && \
    apt-get install -y clang-23 libc++abi-23-dev libc++-23-dev libomp-23-dev flang-23 && \
    apt-get clean

RUN ln -s /usr/bin/clang-23 /usr/bin/clang && \
    ln -s /usr/bin/clang++-23 /usr/bin/clang++

# dependencies
RUN apt-get install -y libjpeg8-dev libpng-dev libtiff-dev make

RUN cd ImageMagick-* && \
    ./configure --prefix=/usr/local/clang CC=clang CXX=clang++ \
        'CXXFLAGS=-stdlib=libc++ -O3 -g' \
        LDFLAGS=-stdlib=libc++ 'LIBS=-lc++ -lc++abi' && \
    make

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y checkinstall llvm-libunwind1 && \
    cd ImageMagick-* && \
    mkdir -p /usr/share/doc/imagemagick-clang23/ && \
    mkdir -p /usr/local/clang/lib && \
    cp LICENSE README.md /usr/share/doc/imagemagick-clang23/ && \
    echo /usr/share/doc/imagemagick-clang23/LICENSE > /tmp/xlist && \
    echo /usr/share/doc/imagemagick-clang23/README.md >> /tmp/xlist && \
    make install && make uninstall && \
    checkinstall -y -D --install=yes --pkgname imagemagick-clang23 \
    --fstrans=no \
    --pkgversion $(basename `pwd` | sed 's/^[^-]*-//') \
    --maintainer "csardi.gabor@gmail.com" \
    --include /tmp/xlist \
    --requires 'libc++1,libc++abi1,llvm-libunwind1,libc6,libgcc-s1,libomp5,zlib1g,libxml2-16,liblzma5,libpng16-16,libjpeg-turbo8,libtiff6,libjbig0' \
    --arch $(dpkg --print-architecture) \
    --pkglicense "See LICENSE file."

RUN cp ImageMagick-*/imagemagick-clang23*.deb /root/

COPY build.sh /root/build.sh
