#! /bin/bash
set -e

checkdir=${1-/check}

do_check () {
    pkg=${1}
    echo Checking "$pkg"
    cd `dirname $pkg`
    R -q -e "pak::pkg_install('deps::$pkg', dependencies = TRUE)"
    R CMD check $CHECK_ARGS $pkg
    packagename=$(basename $pkg | sed "s/_.*$//")
    cd ${packagename}.Rcheck
    fail=false
    exfile="${packagename}-Ex.Rout"
    if [[ -f "${exfile}" ]] && grep -q '^==[0-9][0-9]*==\s*at' ${exfile}; then
        fail=true
        echo ----------------------------------------------------------
        echo ${exfile}
        echo ----------------------------------------------------------
        cat ${exfile}
        echo ----------------------------------------------------------
    fi
    if [[ -d tests ]]; then
        testfiles=$(ls tests | grep ".Rout.fail$")
        for f in $testfiles; do
            if grep -q '^==[0-9][0-9]*==\s*at' tests/$f; then
                fail=true
                echo ----------------------------------------------------------
                echo tests/${f}
                echo ----------------------------------------------------------
                cat tests/${f}
                echo ----------------------------------------------------------
            fi
        done
    fi
    if [[ "$fail" = "true" ]]; then exit 1; fi
}

for pkg in `ls $checkdir/*.tar.gz`; do
    do_check "$pkg"
done
