FROM debian:unstable

ENV OS_IDENTIFIER debian-unstable

RUN set -x \
  && export DEBIAN_FRONTEND=noninteractive \
  && echo 'deb-src http://deb.debian.org/debian sid main' >> /etc/apt/sources.list \
  && apt-get update \
  && apt-get install -y curl gcc libcurl4-openssl-dev libicu-dev \
     libopenblas-dev libpcre2-dev make python3-pip wget \
  && apt-get build-dep -y r-base

# RUN pip3 install awscli

RUN chmod 0777 /opt

RUN curl -LO "https://github.com/goreleaser/nfpm/releases/download/v2.18.1/nfpm_$(dpkg --print-architecture).deb" && \
    apt install -y "./nfpm_$(dpkg --print-architecture).deb" && \
    rm "nfpm_$(dpkg --print-architecture).deb"

# Override the default pager used by R
ENV PAGER /usr/bin/pager

# R 3.x requires PCRE2 for Pango support on Debian 11
ENV INCLUDE_PCRE2_IN_R_3 yes

COPY dockerfiles/package.debian-unstable-devel /package.sh
COPY build.sh .
ENTRYPOINT ./build.sh
