
FROM ubuntu:26.04

WORKDIR /root

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -y && \
    apt-get install -y curl && \
    curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.20.3/protobuf-cpp-3.20.3.tar.gz && \
    tar xzf protobuf-cpp-*.tar.gz && \
    rm protobuf-cpp-*.tar.gz

# ------------------------------------------------------------------------------------
# clang 23

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get install -y gpg && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl https://apt.llvm.org/llvm-snapshot.gpg.key | \
      gpg --dearmor -o /etc/apt/keyrings/apt.llvm.org.gpg

RUN echo "deb [signed-by=/etc/apt/keyrings/apt.llvm.org.gpg] http://apt.llvm.org/resolute/ llvm-toolchain-resolute-23 main" | \
  tee -a /etc/apt/sources.list.d/llvm.list

RUN apt-get update -y && \
    apt-get install -y clang-23 libc++abi-23-dev libc++-23-dev libomp-23-dev flang-23 && \
    apt-get install -y pkg-config make && \
    apt-get clean

RUN ln -s /usr/bin/clang-23 /usr/bin/clang && \
    ln -s /usr/bin/clang++-23 /usr/bin/clang++

RUN cd protobuf-* && \
    ./configure --prefix=/usr/local/clang CC=clang CXX=clang++ \
        'CXXFLAGS=-stdlib=libc++ -O3 -g' \
        LDFLAGS=-stdlib=libc++ 'LIBS=-lc++ -lc++abi' && \
    make

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y checkinstall llvm-libunwind1 && \
    cd protobuf-* && \
    mkdir -p /usr/share/doc/protobuf-clang23/ && \
    cp LICENSE README.md /usr/share/doc/protobuf-clang23/ && \
    echo /usr/share/doc/protobuf-clang23/LICENSE > /tmp/xlist && \
    echo /usr/share/doc/protobuf-clang23/README.md >> /tmp/xlist && \
    checkinstall -y -D --pkgname protobuf-clang23 \
    --pkgversion $(basename `pwd` | sed 's/^[^-]*-//') \
    --fstrans=no \
    --maintainer "csardi.gabor@gmail.com" \
    --include /tmp/xlist \
    --requires 'libc++1,libc++abi1,llvm-libunwind1,libc6,libgcc-s1' \
    --arch $(dpkg --print-architecture) \
    --pkglicense "See LICENSE file."

RUN cp protobuf-*/protobuf-clang*.deb /root/

COPY build.sh /root/build.sh
