
FROM ubuntu:26.04

WORKDIR /root

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -y && \
    apt-get install -y curl && \
    curl -L -o jags.tar.gz \
        https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Source/JAGS-4.3.2.tar.gz/download && \
    tar xzf jags.tar.gz && \
    rm jags.tar.gz

# ------------------------------------------------------------------------------------
# clang 23

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get install -y gpg && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl https://apt.llvm.org/llvm-snapshot.gpg.key | \
      gpg --dearmor -o /etc/apt/keyrings/apt.llvm.org.gpg

RUN echo "deb [signed-by=/etc/apt/keyrings/apt.llvm.org.gpg] http://apt.llvm.org/resolute/ llvm-toolchain-resolute-23 main" | \
  tee -a /etc/apt/sources.list.d/llvm.list

RUN apt-get update -y && \
    apt-get install -y clang-23 libc++abi-23-dev libc++-23-dev libomp-23-dev flang-23 && \
    apt-get install -y pkg-config make gfortran && \
    apt-get clean

RUN ln -s /usr/bin/clang-23 /usr/bin/clang && \
    ln -s /usr/bin/clang++-23 /usr/bin/clang++

# dependencies
RUN apt-get install -y libopenblas-dev

RUN cd JAGS-* && \
    ./configure --prefix=/usr/local/clang CC=clang CXX=clang++ \
        'CXXFLAGS=-stdlib=libc++ -O3 -g' \
        LDFLAGS=-stdlib=libc++ 'LIBS=-lc++ -lc++abi' && \
    make

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y checkinstall llvm-libunwind1 && \
    cd JAGS-* && \
    mkdir -p /usr/share/doc/jags-clang23/ && \
    cp COPYING README INSTALL AUTHORS NEWS /usr/share/doc/jags-clang23/ && \
    echo /usr/share/doc/jags-clang23/COPYING > /tmp/xlist && \
    echo /usr/share/doc/jags-clang23/README >> /tmp/xlist && \
    echo /usr/share/doc/jags-clang23/INSTALL >> /tmp/xlist && \
    echo /usr/share/doc/jags-clang23/AUTHORS >> /tmp/xlist && \
    echo /usr/share/doc/jags-clang23/NEWS >> /tmp/xlist && \
    checkinstall -y -D --pkgname jags-clang23 \
    --fstrans=no \
    --pkgversion $(basename `pwd` | sed 's/^[^-]*-//') \
    --maintainer "csardi.gabor@gmail.com" \
    --include /tmp/xlist \
    --requires 'libc++1,libc++abi1,llvm-libunwind1,libc6,libgcc-s1' \
    --arch $(dpkg --print-architecture) \
    --pkglicense "See LICENSE file."

RUN cp JAGS-*/jags-clang23*.deb /root/

COPY build.sh /root/build.sh
