#! /bin/bash
set -e

checkdir=${1-/check}

do_check () {
    pkg=${1}
    echo Checking "$pkg"
    (
        cd `dirname $pkg`
        R -q -e "pak::pkg_install('deps::$pkg', dependencies = list(direct = 'LinkingTo', indirect = 'hard'))"
	tar xzf $pkg
	descdir="`tar tzf $pkg | grep DESCRIPTION | head -1`"
	package="`dirname $descdir`"
	cd $package
	/opt/R/devel-rchk/bin/rchk.sh
    )
}

for pkg in `ls $checkdir/*.tar.gz`; do
    do_check "$pkg"
done
